project_name: shiitake
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: ./
    binary: shiitake
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  - format: binary
    id: shiitake
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brew:
  github:
    owner: kosa3
    name: homebrew-shiitake
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  description: "shiitake cli"
  homepage: "https://github.com/kosa3/shiitake"
  dependencies:
    - fzf
  install: |
    system 'go', 'build'
    bin.install 'shiitake'
release:
  prerelease: auto